name: fenicsx-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - fenics-dolfinx=0.11.0
  - adios2
  - scipy
  - matplotlib
  - mpich
  - pyvista
  - jupyterlab
  - imageio
  - cmocean
  - pip
  - pip:
      - adios4dolfinx==0.11.0
      - -e .[viz,dev]
